# <job id><program and parameters>
0 python3 -m maploc.evaluation.mapillary_new --experiment OrienterNet_MGL_ft_new model.num_rotations=256 > eval_logs/OrienterNet_MGL_new/mgl_ft_new.log 2>&1
1 python3 -m maploc.evaluation.mapillary_new --experiment OrienterNet_MGL_new_2 model.num_rotations=256 > eval_logs/OrienterNet_MGL_new/mgl_tfs_new.log 2>&1